### ISSUE TITLE
DRIAMS dataset download

### ISSUE THREAD

**Issue by davidshumway** [BorgwardtLab/maldi-learn#1]
Where is the download for this dataset?

**Comment by cvweis** [comment]
The data has not been released yet due to the ongoing review process. We will notify you once the data has been released, thank you for your patience.

**Comment by cgoliver** [comment]
Would this be it? https://datadryad.org/stash/dataset/doi%253A10.5061%252Fdryad.bzkh1899q#:~:text=The%20DRIAMS%20dataset%20is%20ressource,spectra%20in%20the%20form%20of%20.

**Comment by Pseudomanifold** [comment]
Correct! I'll update the README.
