### ISSUE TITLE
Use different models for deep learning

### ISSUE THREAD

**Issue by Kbinn** [BorgwardtLab/maldi-learn#5]
Hello, I want to use bin_6000 files to use different models for deep learning, from your paper we know that there are 6000 feature vectors for each strain, I would like to ask in the DRAIMS folder bin_6000, where can I find the name of the strains in each txt file.

Or is it 2015_clean.cvs against the id file in DRAIMS_A?
Inside, the vertical axis goes to the name of the strain that matches each other.

Thank you for your reply.

**Comment by Pseudomanifold** [comment]
Yes, the file name is a unique ID, with more metadata available in the respective CSV files.
